### ISSUE TITLE
this.$refs[slug] is undefined

### ISSUE THREAD

**Issue by JulesAaelio** [Maximinodotpy/Gitdown#19]
Hi, thanks for working on this plugin, 

I'm facing an issue : 

Version : 1.4.2

**Reproduction steps**:
- Have an unpublished article
- Click Publish 

**Expected behavior**:
- Article is published

**Actual behavior**:
- Nothing happens 

Following error message is displayed in the console : 
```
Uncaught TypeError: this.$refs[slug] is undefined
    update_post http://masked:8080/wp-content/plugins/gitdown/js/admin.js?ver=6.2:48
    VueJS 43
    sync http://masked:8080/wp-content/plugins/gitdown/js/admin.js?ver=6.2:109
    promise callback*sync http://masked:8080/wp-content/plugins/gitdown/js/admin.js?ver=6.2:108
    mounted http://masked:8080/wp-content/plugins/gitdown/js/admin.js?ver=6.2:31
    VueJS 8
    <anonymous> http://masked8080/wp-content/plugins/gitdown/js/admin.js?ver=6.2:120
    EventListener.handleEvent* http://masked:8080/wp-content/plugins/gitdown/js/admin.js?ver=6.2:117
```

**Comment by Maximinodotpy** [comment]
Hey, thank you for your kind words!

I will look into it as soon as I can.

The Frontend is sometimes a little bit janky, a quick reload will often do the trick.

**Comment by Maximinodotpy** [comment]
Hey, my Friend,

So I looked into the issue, and I could fix it, but I don't understand why 😂. Either way, I made another version (1.4.3) so you could make an update and see if it works for you!

Thank you for using this / trying the Plugin!
Also, don't hesitate to open other issues for mistakes or enhancements!
