### ISSUE TITLE
Does it work with private repos?

### ISSUE THREAD

**Issue by trainingcity** [Maximinodotpy/Gitdown#29]
I am looking for a WP plugin that can connect private repos to content in a LearnDash LMS course. The courses are not public and the repos are private. It seems like the older https://github.com/gis-ops/wordpress-markdown-git does support private repos but the code base is not very active, last update was two years ago.

**Comment by Maximinodotpy** [comment]
Hey Friend, so at the moment, there is no beautiful UI for Private Repositories, but you can still use private repos by using authentication data in the URL.

See the following two links for Help.

- [Creating a URL to clone Private Github Repos](https://stackoverflow.com/questions/22755268/clone-a-private-repo-of-github-with-username-and-password)
- [Creating a custom Personal Access Token](https://docs.github.com/de/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)

Please don't hesitate do ask further questions or open Issues,if this plugin would be something for your use case I would love to work with you to make it fit you better! Thank you.

**Comment by Maximinodotpy** [comment]
I also just added this info to the [Faq](https://github.com/Maximinodotpy/Gitdown/blob/master/docs/faq.md)
