### ISSUE TITLE
Cannot read Name property

### ISSUE THREAD

**Issue by bellons91** [Maximinodotpy/Gitdown#3]
When importing some articles, the extension tells that the name property cannot be found on MarkDown.

![image](https://user-images.githubusercontent.com/6106586/225037034-1ea3b31d-a178-4792-a468-e47e69c4b4af.png)

Yet, as you can see on the file I'm trying to import, the Name property does exist.

https://github.com/code4it-dev/wp-articles/blob/main/2023/092-linq-differences/article.md

Am I missing something?

(ps: there's a typo in the message on the UI: _shows no**w** name_

**Comment by Maximinodotpy** [comment]
Hey once again thank you!

I spent a little (bit too much time on this issue) and I think I have a fix.

I made an update adressing this and the earlier issue -> 1.0.6.
you should be able to update through the wordpress UI.

(ps: I also fixed the type but there are probably more :) )

**Comment by bellons91** [comment]
Current version: 6.1.1
Last checked on March 15, 2023 at 12:57 pm

**Comment by Maximinodotpy** [comment]
Ok and what plugins and php version are you using?

**Comment by Maximinodotpy** [comment]
Hey Friend I havent heard back from you are you still experiencing the problems?
