### ISSUE TITLE
Some kind of logging to help understand repository issues

### ISSUE THREAD

**Issue by JSaaS** [Maximinodotpy/Gitdown#7]
I've tried for an hour or so now, but I can't get it to access my repository at all. Completely blind and the only text I've got to go on is in the "Report" section. It would be helpful to throw out the GIT error to help understand why Gitdown can't reach the repository.

/Joakim

**Comment by Maximinodotpy** [comment]
Hey, First off, thank you for trying my plugin!

Let's fix this together.

I will look into making this feature.

But for now, the only thing I want to ask is whether your repository is private or public because, currently, only public repositories work.

**Comment by JSaaS** [comment]
Hi,

I tried both a public and a private repository. Neither worked for me.

/Joakim

**Comment by Maximinodotpy** [comment]
Hey, would it be possible for you to send me the link to a repository that did not work?

also, did you link the .git file or just the URL of the repo because you have to link to the .git file?

**Comment by JSaaS** [comment]
Sure:

https://github.com/JSaaS/Blog.git

**Comment by Maximinodotpy** [comment]
Hey Friend, 

So I tried it out with your repository, and it worked for me. Maybe you did not set a correct glob pattern.

![image](https://user-images.githubusercontent.com/85794303/234769977-014851e0-32e4-4a69-9a64-d87bdfc433e3.png)

And in your article, you need to remove the backticks around the meta information so it reads correctly.

![image](https://user-images.githubusercontent.com/85794303/234770381-fe777a7d-0174-4fc2-8dfd-1ba8783a275a.png)

In the next update I will add the git error to the reports section.

I hope I could help you, if not don't hesitate to reach out.

**Comment by JSaaS** [comment]
Sorry to wake up an old thread. Just had some minutes over for this. I can't seem to get it to work.  Deleted the ticks as you mentioned. Tried to update the settings. only having '*.md* as glob-pattern. Nothing picked up? But, with the latest version of GitDown I can see the following error: 'Git clone failed'. Can this be an error related to my web hotel?

**Comment by Maximinodotpy** [comment]
Hey Friend, no worries im glad someone reached out and points out mistakes!

First, to get a markdown in the root directory, you must use `*.md` where `*` is any number of any character.

Then next up, the directory issue is a weird mistake I made it will be fixed in the next release; you can just delete this rogue wp-content folder.

Lastly, what do you mean by Web Hotel? do you mean web hosting? In the error panel, it should say more things like the git error that occurred.

**Comment by JSaaS** [comment]
Thanks for a quick response!

The rogue folder reappeared after deleting, but I guess this is something you need to push out a new version to fix?

<img width="250" alt="image" src="https://github.com/Maximinodotpy/Gitdown/assets/14349335/30832759-a418-4c7b-b7c3-90af1f424b66">

**Comment by Maximinodotpy** [comment]
Yes, I just pushed the changes. You should see the update in your dashboard and update to 1.4.4.
